### ISSUE TITLE
reduce(*cat, xs) drops keys `*cat(xs...)` is all good though

### ISSUE THREAD

**Issue by oxinabox** [mcabbott/AxisKeys.jl#53]
```
julia> xs = [KeyedArray(i.*[1,2,3], foo=[:a,:b,:c]) for i in 1:4];

julia> hcat(xs...)
2-dimensional KeyedArray(NamedDimsArray(...)) with keys:
↓   foo ∈ 3-element Vector{Symbol}
→   _ ∈ 4-element OneTo{Int}
And data, 3×4 Matrix{Int64}:
        (1)  (2)  (3)  (4)
  (:a)    1    2    3    4
  (:b)    2    4    6    8
  (:c)    3    6    9   12

julia> reduce(hcat, xs)
3×4 Matrix{Int64}:
 1  2  3   4
 2  4  6   8
 3  6  9  12
```
I suspect there is also a NamedDims Array bug since it also drops names

`vcat` doesn't drop names, just keys..
though also it is interesting to note `vcat(ys...)` it allows duplicate keys, which is probably not a feature
```julia
julia> ys = [KeyedArray(i.*[1,2,3]', bar=[:x], foo=[:a,:b,:c]) for i in 1:4];

julia> vcat(ys...)
2-dimensional KeyedArray(NamedDimsArray(...)) with keys:
↓   bar ∈ 4-element Vector{Symbol}
→   foo ∈ 3-element Vector{Symbol}
And data, 4×3 Matrix{Int64}:
        (:a)  (:b)  (:c)
  (:x)   1     2     3
  (:x)   2     4     6
  (:x)   3     6     9
  (:x)   4     8    12

julia> reduce(vcat, ys)
4×3 NamedDimsArray(::Matrix{Int64}, (:bar, :foo)):
       → foo
↓ bar  1  2   3
       2  4   6
       3  6   9
       4  8  12
```

**Comment by mcabbott** [comment]
Thanks, `reduce(hcat, xs)` is indeed missing. I think it drops names because it falls all the way back to an `AbstractArray` method, not because of a bug. But I think `reduce(vcat, xs)` works only because of a bug in `similar`:
```julia
julia> similar(xs[1], 99)
99-element NamedDimsArray(::Vector{Int64}, (:foo,)):
↓ foo  4573916528
       4573916672
       4573916720
       4573916768
```

> note vcat(ys...) it allows duplicate keys

This is a feature, I think, or certainly a decision. The key vectors can be any `AbstractVector`s, there is no assumption that they have unique entries. You are welcome to store categorical labels like `["cat", "dog", "cat"]` there, if that makes sense for what you're doing.
